### ISSUE TITLE
Use `AssignExpression` in all frontends

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#1260]
We should use the `AssignExpression` instead of a `BinaryOperator` with a `==`

```[tasklist]
### Tasks
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/1263
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/1269
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/1262
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/1261
- [x] Use `AssignExpression` in TypeScript
- [x] Use `AssignExpression` in Go
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/1071
```
