### ISSUE TITLE
Replace UnaryOperator "throw" with new `ThrowStatement`

### ISSUE THREAD

**Issue by KuechA** [Fraunhofer-AISEC/cpg#1817]
* [x] Java frontend: See #1814
* [ ] CXX frontend: See #1815 
* [x] LLVM frontend and extra pass: See #1816 

The other frontends do not use this expression.

* [ ] Delete the code handling these things in the EOGPass and the spec
