### ISSUE TITLE
Schedule 3.4 Release

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#355]
I would propose scheduling the release 3.4 within this march.

Let's close up the following PRs and then merge it

# Changelog

- [x] Introduce ParameterizedType for Graph Consistency (#317)
- [x] Deprecate old CFG pass (#345)
- [x] Handling typedefs with tabs (#332)
- [x] Improve Java FQN type guessing (#331)
- [x] Experimental Golang support (#350)
- [x] Better call resolving (#352)
