### ISSUE TITLE
Python: Todo list

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#394]
The experimental python branch has been merged to master. It currently supports some python language features but is far from complete. This issue is supposed to track open todos for the python implementation.

- [ ] Correctly handle "self"
- [ ] Correctly handle an `__init__`call
- [ ] Correctly handle imports / alias imports
- [ ] Implement support for multiple return values
- [ ] Split implementation into multiple files
- [ ] Publish to pip (to be discussed)
- [ ] Resolve all "not implemented" errors

**Comment by KuechA** [comment]
Some notes concerning the above tasks:

## Add declaration pass: traverse EOG instead of AST

This doesn't work because the Pass dependencies don't allow it.

## constant propagation ((multi) value evaluator)

What is expected here? Basic concepts are available (i.e., +, -, etc.) If we need some specific information in a special scenario, we should probably extract this to another evaluator

## Field initializes

What should we do here? This needs a more precise description

## Slices (DFG)

Task description too imprecise

## Match

Basic support/implementation in #1801 . Many of the cases are missing.
