### ISSUE TITLE
Overhaul of the type system

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#705]
```[tasklist]
### Tasks
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/29
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/691
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/204
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/189
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/28
- [ ] https://github.com/Fraunhofer-AISEC/cpg/issues/512
```
